//----------------------
// <auto-generated>
//     Generated using the NSwag toolchain v13.2.2.0 (NJsonSchema v10.1.4.0 (Newtonsoft.Json v12.0.0.0)) (http://NSwag.org)
// </auto-generated>
//----------------------

using System;
using System.Collections.Generic;
using System.Runtime.Serialization;
using Newtonsoft.Json;

namespace StudyTogether
{
    [Serializable]
    internal class ApiException : Exception
    {
        private string message;
        private int statusCode;
        private string empty;
        private IReadOnlyDictionary<string, IEnumerable<string>> headers;
        private JsonException exception;

        public ApiException()
        {
        }

        public ApiException(string message) : base(message)
        {
        }

        public ApiException(string message, Exception innerException) : base(message, innerException)
        {
        }

        public ApiException(string message, int statusCode, string empty, IReadOnlyDictionary<string, IEnumerable<string>> headers, JsonException exception)
        {
            this.message = message;
            this.statusCode = statusCode;
            this.empty = empty;
            this.headers = headers;
            this.exception = exception;
        }

        protected ApiException(SerializationInfo info, StreamingContext context) : base(info, context)
        {
        }
    }
}